# Generated by Django 5.2 on 2025-05-02 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_message', models.TextField()),
                ('ai_response', models.TextField()),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_inputs/')),
                ('response_audio', models.FileField(blank=True, null=True, upload_to='audio_responses/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
